Repository Automattic/a8c-ci-toolkit-buildkite-plugin, pull requests merged in 2024-09, with the labels that each got.

#112 Update CHANGELOG for #105
  CHANGELOG.md
Labels: documentation

#113 [Tooling] Setup Dangermattic
  .buildkite/pipeline.yml
  .bundle/config
  .github/workflows/run-danger.yml
  .gitignore
  CHANGELOG.md
  Dangerfile
  Gemfile
  Gemfile.lock
Labels: tooling

#115 [Tooling] Add `github_commit_status` to all pipeline jobs
  .buildkite/pipeline.yml
Labels: tooling

#116 Check for `$BUILDKITE_PULL_REQUEST = false` when uploading sarif file.
  CHANGELOG.md
  bin/upload_sarif_to_github
Labels: bug

#118 Fix passing branch name when sending sarif fail
  bin/upload_sarif_to_github
Labels: bug

#120 Comment with dependency diff
  CHANGELOG.md
  bin/comment_on_pr
  bin/comment_with_dependency_diff
Labels: enhancement

#122 Append "tldr" to dependency diff
  CHANGELOG.md
  bin/comment_with_dependency_diff
  jar/dependency-diff-tldr-0.0.6.jar
Labels: enhancement

#124 Use BUILDKITE_REPO to retrieve repo owner and name
  CHANGELOG.md
  bin/upload_sarif_to_github
Labels: bug

#127 Fix logic of github_api to autodetect host
  CHANGELOG.md
  bin/github_api
Labels: bug
