Repository Automattic/a8c-ci-toolkit-buildkite-plugin, pull requests merged in 2025-03, with the labels that each got.

#169 Release 5.1.0
  CHANGELOG.md
  README.md
Labels: release

#170 Make tldr part `diff` and colorize headers
  bin/comment_with_dependency_diff
  bin/craft_comment_with_dependency_diff
Labels: enhancement

#172 `5.1.2` release
  CHANGELOG.md
  README.md
Labels: release

#174 Release 5.1.3
  CHANGELOG.md
  README.md
Labels: release

#175 [CI] Enhance Annotate Test Failures Script with Optional Module Name
  CHANGELOG.md
  bin/annotate_test_failures
Labels: tooling

#177 [Diff] Enhance Comment with Dependency/Manifest Diff with Git Fetch/Pull
  CHANGELOG.md
  bin/comment_with_dependency_diff
  bin/comment_with_manifest_diff
Labels: tooling

#178 Release 5.3.0
  CHANGELOG.md
  README.md
Labels: release
